### ISSUE TITLE
Recovering problem with persistent storage enabled

### ISSUE THREAD

**Issue by martianoff** [rabbitmq/rabbitmq-peer-discovery-k8s#21]
Kubernetes deployment based on rabbitmq-peer-discovery-k8s and persistent storage has problem with "inconsistent_cluster" boot after crash

Steps to reproduce and more info here:

[https://github.com/kubernetes/charts/issues/4474](https://github.com/kubernetes/charts/issues/4474)
[https://github.com/kubernetes/charts/issues/4519](https://github.com/kubernetes/charts/issues/4519)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
This is very likely a just another manifestation of a scenario described [in this rabbitmq-users thread](https://groups.google.com/forum/#!searchin/rabbitmq-users/rabbitmq-peer-discovery-k8s|sort:date/rabbitmq-users/VlRl4UMiG9Y/gLWZhBeTDAAJ) and #12.

This plugin has a specific scope: peer discovery. It is not a panacea or guarantee that under all circumstances a cluster will be formed and will be in perfect shape.

**Comment by michaelklishin** [comment]
There is absolutely no evidence in the linked issues of a problem in this plugin.

**Comment by michaelklishin** [comment]
This [rabbitmq-users response](https://groups.google.com/d/msg/rabbitmq-users/wuOfzEywHXo/k8z_HWIkBgAJ) provides a very plausible hypothesis: [automatic forced cleanup of unknown nodes](http://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup) was enabled in the [Kubernetes example](https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/blob/b309d641ce7ccf135d02fb39254e8c67c98d3a63/examples/k8s_statefulsets/rabbitmq_statefulsets.yaml#L40). Unintended removal of nodes temporarily leaving the cluster is one of the consequences of that decision, and apparently a pod restart can trigger it.
