### ISSUE TITLE
RabbitMQ Kubernetes pod getting restared

### ISSUE THREAD

**Issue by AnudeepKumarDonthu** [rabbitmq/rabbitmq-peer-discovery-k8s#43]
Hi Team,

System Information:
=============================================================
Helios 7.6 SP 1,
Kubernetes Version v1.14.1
docker version 18.09.5
helm version v2.13.1

Issue Details:
=============================================================
I am deploying Rabbitmq in a kubernetes pod with helm chat and the pod is getting restarted continuously, then I checked the logs of rabbitmq-ha the I found below error message, I am not sure how to fix this error, please help in resolving the  issue.

Error in the Log: command to get below log (kubectl logs rabbitmq-rabbitmq-ha-0 rabbitmq-ha)
=============================================================
2019-04-25 08:58:41.319 [error] <0.281.0> CRASH REPORT Process <0.281.0> with 0 neighbours exited with reason: {error,not_json} in application_master:init/4 line 138
2019-04-25 08:58:41.320 [info] <0.43.0> Application rabbit exited with reason: {error,not_json}
{"Kernel pid terminated",application_controller,"{application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{error,not_json}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{error,not_json}}}}})

Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
All this tells us is that a file (likely [with definitions](https://www.rabbitmq.com/management.html#load-definitions) was expected to contain valid JSON but did not). This plugin has nothing to do with that.
