### ISSUE TITLE
sed: couldn't open temporary file /etc/rabbitmq/sedl0t5ty: Read-only file system

### ISSUE THREAD

**Issue by dingsongjie** [rabbitmq/rabbitmq-peer-discovery-k8s#47]
If I add my custom user by using RABBITMQ_DEFAULT_USER , It faild with 
```cs
sed: couldn't open temporary file /etc/rabbitmq/sedl0t5ty: Read-only file system
```

**Comment by dingsongjie** [comment]
I solved it by using init container  cope configs  to a  shared emptyDir ,and then amount it.
I want to ask if there is a better solution?

**Comment by hnpatadia** [comment]
Hi @dingsongjie can you please share your volume mount code. I did emptyDir thing  but still it does not work.

**Comment by dingsongjie** [comment]
Hi ,Sorry to reply a bit late,this is my config.There is a part of helm's
syntax, but I think you should be able to understand.

apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: {{ .Values.rabbitmq.namespace }}
data:
  enabled_plugins: |

[rabbitmq_shovel,rabbitmq_shovel_management,rabbitmq_management,rabbitmq_peer_discovery_k8s].

  rabbitmq.conf: |
      ## Cluster formation. See
https://www.rabbitmq.com/cluster-formation.html to learn more.
      cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      ## Should RabbitMQ node name be computed from the pod's hostname or
IP address?
      ## IP addresses are not stable, so using [stable] hostnames is
recommended when possible.
      ## Set to "hostname" to use pod hostnames.
      ## When this value is changed, so should the variable used to set the
RABBITMQ_NODENAME
      ## environment variable.
      cluster_formation.k8s.address_type = hostname
      ## How often should node cleanup checks run?
      cluster_formation.node_cleanup.interval = 30
      ## Set to false if automatic removal of unknown/absent nodes
      ## is desired. This can be dangerous, see
      ##  *
https://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup
      ##  *
https://groups.google.com/forum/#!msg/rabbitmq-users/wuOfzEywHXo/k8z_HWIkBgAJ
      cluster_formation.node_cleanup.only_log_warning = true
      cluster_partition_handling = autoheal
      ## See https://www.rabbitmq.com/ha.html#master-migration-data-locality
      queue_master_locator=min-masters
      ## See https://www.rabbitmq.com/access-control.html#loopback-users
      #loopback_users.guest = false
      listeners.tcp.default = 5672
      default_pass = 123123
      default_user = 123123
      management.listener.port = 15672
      management.listener.ssl = false
      cluster_formation.k8s.hostname_suffix =
.rabbitmq.rabbitmq.svc.cluster.local
      vm_memory_high_watermark.relative = 0.4
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: {{ .Values.rabbitmq.namespace }}
spec:
  serviceName: rabbitmq
  replicas: {{ .Values.rabbitmq.replicas }}
  template:
    metadata:
      labels:
        component: rabbitmq
    spec:
      dnsConfig:
        searches:
          - rabbitmq.rabbitmq.svc.cluster.local
      serviceAccountName: rabbitmq
      affinity:
{{- toYaml .Values.rabbitmq.affinity | nindent 8 }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image }}
        resources:
{{- toYaml .Values.rabbitmq.resources | nindent 10 }}
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_Host_Name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
          # See a note on cluster_formation.k8s.address_type in the config
file section
        - name: RABBITMQ_NODENAME
          value: "rabbit@
$(MY_POD_Host_Name).rabbitmq.rabbitmq.svc.cluster.local"
        - name: K8S_SERVICE_NAME
          value: "rabbitmq"
        - name: RABBITMQ_ERLANG_COOKIE
          value: "rabbitmq-k8s-default"
        - name: TZ
          value: Asia/Shanghai
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: '-rabbitmq_management path_prefix "/rabbitmq"'
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: http
        - name: epmd
          protocol: TCP
          containerPort: 4369
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
        - name: config-from-volume
          mountPath: /etc/rabbitmq
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 60
          # See https://www.rabbitmq.com/monitoring.html for monitoring
frequency recommendations.
          periodSeconds: 60
          timeoutSeconds: 15
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 20
          periodSeconds: 60
          timeoutSeconds: 10
      volumes:
        - name: config-from-volume
          configMap:
            name: rabbitmq-config
            items:
            - key: rabbitmq.conf
              path: rabbitmq.conf
            - key: enabled_plugins
              path: enabled_plugins
