### ISSUE TITLE
Create examples for K8s

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-peer-discovery-k8s#5]
Create examples for K8s backend

**Comment by nhumrich** [comment]
Along these lines: please provide an example of how to use this without pivitols prebuilt docker container.

**Comment by michaelklishin** [comment]
[There are examples](http://www.rabbitmq.com/cluster-formation.html) for this backend.

There are many aspects to automating cluster formation that have nothing to do with peer discovery. @Gsantomaggio and I agree that we should either include a docker file or try to base this on the [Docker Inc's image](https://github.com/docker-library/rabbitmq) but that image was not built for such peer discovery mechanisms, so at best we will have to tweak things moderately and try to contribute some of the change back.

Secret management (for the Erlang cookie) is one obvious missing piece. So far we are not sure if it's worth maintaining our own image for such things.

**Comment by Gsantomaggio** [comment]
@nhumrich we changed from pivotal docker image to official docker image.

see: https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/pull/13 

[Here]( https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/tree/v3.7.x/examples/k8s_statefulsets) you can find the new example

**Comment by michaelklishin** [comment]
@Gsantomaggio should we close this?

**Comment by Gsantomaggio** [comment]
@michaelklishin yes I think so
