### ISSUE TITLE
Nodes fail to cluster because their Erlang cookies are out of sync

### ISSUE THREAD

**Issue by cap10morgan** [rabbitmq/rabbitmq-peer-discovery-k8s#8]
When using the example k8s resources in this repo, the RabbitMQ nodes fail to cluster because their Erlang cookie values are out of sync.

Would it make sense to automate that at some level as a part of the new peer discovery system?

At the very least documenting a good way to set that cluster-wide and/or adding it to the example would be good.

**Comment by michaelklishin** [comment]
No, Erlang cookie management is out of scope for RabbitMQ, its peer discovery mechanism and so on. Data services should not manage their own secrets. Kubernetes/Docker images, BOSH, Chef, Puppet, etc should.

We used to have a note in https://github.com/rabbitmq/rabbitmq-autocluster that said: "this plugin is not a substitute for understanding of how RabbitMQ nodes are clustered."

That's still my position.

**Comment by cap10morgan** [comment]
OK, so that's a big "no" on the automation question. Makes sense.

But that still leaves this as a non-working example. It is neither documented nor correct as is. The nodes do not cluster because of this even though the supplied k8s resource files imply that they should. And I have found no docs nor any experimental way to fix that.

I understand how RabbitMQ nodes are clustered. What I'm looking for is a little guidance of how I should sync the Erlang cookie in order to actually make this k8s example work. I've done it many different ways in the past, but none of them work w/ this example so far.

What I've tried:

- Setting the `RABBITMQ_ERLANG_COOKIE` env var: This Docker image doesn't appear to do anything with that like the official `rabbitmq` image does.
- Setting the `ERLANG_COOKIE` env var (as the rabbitmq-autocluster's [minikube example does](https://github.com/rabbitmq/rabbitmq-autocluster/blob/master/examples/k8s_minikube/rabbitmq.yaml#L25-L26): Also doesn't seem to be respected by the `pivotalrabbitmq/rabbitmq-autocluster:3.7-k8s-BETA` Docker image.
- Mounting a k8s Secret volume at `/var/lib/rabbbitmq/.erlang.cookie`: Fails when the container's entrypoint `/launch.sh` script tries to run `chown -R rabbitmq:rabbitmq /var/lib/rabbitmq` because the secret volume is read-only.

Does anyone actually have this working anywhere? If so, how did they set a cluster-wide Erlang cookie? Could they maybe throw that in a document somewhere or add it to the YAML files in the example?

**Comment by michaelklishin** [comment]
This example should do the same thing as the one in rabbitmq-autocluster. I suspect it's simply out of date.

@Gsantomaggio would you agree?

**Comment by Gsantomaggio** [comment]
@michaelklishin The example works correctly:

I just tried it:

![screen shot 2017-10-19 at 19 15 50](https://user-images.githubusercontent.com/386987/31784468-1032949c-b502-11e7-96fd-0c75a3d5010b.png)

On the image `pivotalrabbitmq/rabbitmq-autocluster:3.7-k8s-BETA` is not possible to set the cookie. 

We build this image only to run the examples, we don't want to create another "Official RabbitMQ Docker Image" 


@cap10morgan [This](https://github.com/rabbitmq/rabbitmq-autocluster/blob/master/examples/k8s_minikube/rabbitmq.yaml#L25-L26) is an error in the YAML file, in our images, it is not possible to set the cookies

**Comment by cap10morgan** [comment]
OK then I’m very confused. When I run the example the Erlang cookies are all different and the logs show the other nodes being blocked from communicating because of that.

Oh, I bet I know why: It’s because I’m putting `/var/lib/rabbitmq` on a persistent volume. I do that so that the node’s state will be maintained across pod restarts so they can re-join the cluster, etc.

Is that no longer necessary with the k8s peer discovery system in 3.7.x?

**Comment by Gsantomaggio** [comment]
@cap10morgan yes, you are overriding the `/var/lib/rabbitmq/` .
if you remove the persistent volume, it should work! :)

**Comment by cap10morgan** [comment]
@Gsantomaggio In the past, keeping `/var/lib/rabbitmq` on a persistent volume has been critical for allowing RabbitMQ nodes to re-join their clusters after restarting. Will that now happen without a persistent volume with the new k8s peer discovery system?

**Comment by michaelklishin** [comment]
We could use a hardcoded Erlang cookie value of "example" in this image. I'm concerned that some may end up deploying it into production because YOLO.

**Comment by michaelklishin** [comment]
@cap10morgan this is simply an example. Obviously a node without its data on a persistent volume is not something that many can deploy but it will discover its peers via Kubernetes and join the cluster. Combined with the automatic node cleanup feature, it might even work decently.

@Gsantomaggio I think we should make the persistent volume scenario work, hardcoding a cookie and placing a VISIBLE WARNING that this is simply an example should be OK. We also can base our example images on the official one to make them more configurable and make the gap between the example and a realistic system smaller.

**Comment by Gsantomaggio** [comment]
@michaelklishin yes, it makes sense.

**Comment by cap10morgan** [comment]
Sounds good, thanks all.

And yes, I realize this is a non-production-ready example. I'm just trying it out in a development environment to get an idea of how things will work in 3.7.x. I assume there will be a new official `rabbitmq` Docker image released with the final 3.7.0 release that will hopefully contain all of the new peer discovery plugins and continue respecting the `RABBITMQ_ERLANG_COOKIE` env var?

**Comment by michaelklishin** [comment]
It's a question for the Docker image maintainers (which, contrary to a popular believe, are not Team RabbitMQ). They have [a prototype PR](https://github.com/docker-library/rabbitmq/pull/197) which does not cover peer discovery at the moment but it would be cool if it made that easier.
