### ISSUE TITLE
Release 3.7.0 version

### ISSUE THREAD

**Issue by JorisAndrade** [rabbitmq/rabbitmq-peer-discovery-k8s#9]
Hi guys,

Is it possible to release a new version on https://hub.docker.com/r/pivotalrabbitmq/rabbitmq-autocluster/tags/. 

Only the beta tag is available.

Thanks!

**Comment by Gsantomaggio** [comment]
Hi @JorisAndrade 

Updated the [example](https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/tree/master/examples/k8s_statefulsets) and the [docker image](https://hub.docker.com/r/pivotalrabbitmq/rabbitmq-autocluster/tags/)
